name: autoortho
channels:
  - conda-forge
dependencies:
  - python=3.11
  - certifi
  - nuitka
  - zstandard
  - ordered-set
  - pysimplegui
  - eventlet
  - packaging
  - Flask
  - flask-socketio
  - psutil
  - geocoder
  - imageio
  - libjpeg-turbo